"""Generate V2 figures matching the ones app.py displays.

Outputs to figures_v2/:
  - v2_shap_summary.png   (beeswarm)
  - v2_shap_bar.png       (already generated by experiment_v2.py, regenerated here for completeness)
  - v2_kmeans_pca.png
  - v2_churn_per_cluster.png
  - v2_clv_per_cluster.png
  - v2_clv_vs_churn_scatter.png
"""
import sys, io, os, pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import shap

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

sns.set_theme(style="whitegrid")
plt.rcParams["figure.dpi"] = 100
plt.rcParams["savefig.dpi"] = 150
plt.rcParams["font.sans-serif"] = ["Microsoft JhengHei", "DejaVu Sans"]
plt.rcParams["axes.unicode_minus"] = False

FIG_DIR = "figures_v2"
os.makedirs(FIG_DIR, exist_ok=True)
RANDOM_STATE = 42

FEATURES_V2 = [
    "gender", "Near_Location", "Partner", "Promo_friends", "Phone",
    "Contract_period", "Group_visits", "Age",
    "Avg_additional_charges_total", "months_into_current",
    "Lifetime",
    "Avg_class_frequency_total", "Avg_class_frequency_current_month",
]
SIGNUP_FEE = 500
MONTHLY_FEE = 1100

df = pd.read_csv("data/gym_churn_us.csv")
df["months_into_current"] = df["Contract_period"] - df["Month_to_end_contract"]

X = df[FEATURES_V2]
y = df["Churn"]

with open("xgb_churn_model_v2.pkl", "rb") as f:
    xgb_v2 = pickle.load(f)

# ---- SHAP summary + bar ----
print("Generating SHAP plots...")
explainer = shap.TreeExplainer(xgb_v2)
shap_values = explainer.shap_values(X)

shap.summary_plot(shap_values, X, show=False)
plt.gcf().set_size_inches(10, 6)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_shap_summary.png", bbox_inches="tight")
plt.close()

shap.summary_plot(shap_values, X, plot_type="bar", show=False)
plt.gcf().set_size_inches(9, 5)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_shap_bar.png", bbox_inches="tight")
plt.close()

# ---- K-means + PCA ----
print("Running K-means + PCA...")
scaler = StandardScaler().fit(X)
X_scaled = scaler.transform(X)
km = KMeans(n_clusters=4, random_state=RANDOM_STATE, n_init=10).fit(X_scaled)
df["cluster"] = km.labels_

pca = PCA(n_components=2, random_state=RANDOM_STATE)
coords = pca.fit_transform(X_scaled)
fig, ax = plt.subplots(figsize=(8, 6))
palette = ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728"]
for c in sorted(df["cluster"].unique()):
    mask = df["cluster"] == c
    ax.scatter(coords[mask, 0], coords[mask, 1], s=10, alpha=0.5,
               color=palette[c], label=f"Cluster {c} (n={mask.sum()})")
ax.set_xlabel(f"PC1 ({pca.explained_variance_ratio_[0]:.1%})")
ax.set_ylabel(f"PC2 ({pca.explained_variance_ratio_[1]:.1%})")
ax.set_title("K-means 分群（V2 特徵、PCA 2D 投影）")
ax.legend(loc="best", fontsize=9)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_kmeans_pca.png")
plt.close()

# ---- Churn per cluster ----
fig, ax = plt.subplots(figsize=(8, 5))
churn_by_cluster = df.groupby("cluster")["Churn"].mean().sort_values()
bar_colors = ["#4CAF50", "#8BC34A", "#FFC107", "#F44336"]
churn_by_cluster.plot(kind="bar", color=bar_colors, ax=ax)
ax.set_title("各群流失率（V2，排序由低到高）")
ax.set_ylabel("流失率")
ax.set_xlabel("Cluster")
for i, v in enumerate(churn_by_cluster.values):
    ax.text(i, v + 0.005, f"{v:.1%}", ha="center", fontsize=11)
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_churn_per_cluster.png")
plt.close()

# ---- CLV per cluster ----
print("Computing CLV...")
churn_proba = xgb_v2.predict_proba(X)[:, 1]
df["churn_proba"] = churn_proba
df["stay_proba"] = 1 - churn_proba

# m2e = Contract_period - months_into_current (derived back for CLV business calc)
df["m2e_derived"] = df["Contract_period"] - df["months_into_current"]

df["historical_CLV"] = SIGNUP_FEE + df["Lifetime"] * MONTHLY_FEE + df["Avg_additional_charges_total"]
df["expected_future_revenue"] = df["stay_proba"] * df["m2e_derived"].clip(lower=0) * MONTHLY_FEE
df["expected_CLV"] = df["historical_CLV"] + df["expected_future_revenue"]

clv_summary = df.groupby("cluster").agg(
    historical_CLV=("historical_CLV", "mean"),
    future_revenue=("expected_future_revenue", "mean"),
    total_CLV=("expected_CLV", "mean"),
    churn_rate=("Churn", "mean"),
    size=("Churn", "count"),
).round(0).sort_values("total_CLV", ascending=False)

fig, ax = plt.subplots(figsize=(10, 5))
plot_df = clv_summary.reset_index()
x = np.arange(len(plot_df))
width = 0.35
ax.bar(x - width/2, plot_df["historical_CLV"], width,
       color="#4CAF50", label="歷史 CLV（已賺到）")
ax.bar(x + width/2, plot_df["future_revenue"], width,
       color="#FFC107", label="預期未來營收")
ax.set_xticks(x)
ax.set_xticklabels([f"Cluster {int(c)}" for c in plot_df["cluster"]])
ax.set_ylabel("NT$")
ax.set_title("各群平均 CLV 構成（V2 / chocoZAP 台北費率）")
ax.legend()
for i, (h, f_) in enumerate(zip(plot_df["historical_CLV"], plot_df["future_revenue"])):
    ax.text(i - width/2, h + 100, f"{h:,.0f}", ha="center", fontsize=9)
    ax.text(i + width/2, f_ + 100, f"{f_:,.0f}", ha="center", fontsize=9)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_clv_per_cluster.png")
plt.close()

# ---- CLV vs churn scatter ----
fig, ax = plt.subplots(figsize=(10, 6))
scatter = ax.scatter(df["churn_proba"], df["expected_CLV"],
                      c=df["cluster"], cmap="tab10", alpha=0.5, s=12)
ax.set_xlabel("XGBoost 預測的流失機率")
ax.set_ylabel("預期 CLV (NT$)")
ax.set_title("每位客戶：流失機率 × 預期 CLV（V2）")
legend = ax.legend(*scatter.legend_elements(), title="Cluster", loc="upper right")
ax.add_artist(legend)
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/v2_clv_vs_churn_scatter.png")
plt.close()

print(f"\n[done] {len(os.listdir(FIG_DIR))} figures in {FIG_DIR}/")
for f in sorted(os.listdir(FIG_DIR)):
    p = os.path.join(FIG_DIR, f)
    print(f"  {os.path.getsize(p)//1024:>6d} KB  {f}")
